Default: &defaults
  user: yesog
  password: yesog
  host: localhost
  database: yesog
  connections: 10

Development:
  <<: *defaults

Testing:
  database: yesog_test
  <<: *defaults

Staging:
  database: yesog_staging
  connections: 100
  <<: *defaults

Production:
  database: yesog_production
  connections: 100
  host: localhost
  <<: *defaults
